apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-aws
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abaguas/k8gb-v0.15-demo
    targetRevision: HEAD
    path: podinfo-aws
    helm:
      valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo-aws
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
