apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8gb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abaguas/k8gb-v0.15-demo
    targetRevision: HEAD
    path: k8gb-eu
    helm:
      valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: k8gb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
