k8gb:
  coredns:
    serviceType: LoadBalancer
    deployment:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb

  k8gb:
    dnsZone: cloud.k8gb.website
    edgeDNSZone: k8gb.website
    dnsZoneNegTTL: 300
    edgeDNSServers:
    - 169.254.169.253
    clusterGeoTag: eu
    extGslbClustersGeoTags: us

  route53:
    enabled: true
    hostedZoneID: Z0558249124TGIA4RDL27
    irsaRole: arn:aws:iam::600627351764:role/external-dns-irsa-role
