apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  name: proxy-lb
  namespace: istio-ingress
spec:
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: istio-ingress
    istio: ingress
  type: LoadBalancer
