---
apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: podinfo
spec:
  resourceRef:
    apiVersion: networking.istio.io/v1
    kind: VirtualService
    matchLabels:
      app: podinfo
  strategy:
    type: failover
    dnsTtlSeconds: 5
    primaryGeoTag: "eu"
