---
apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: podinfo
  annotations:
    k8gb.io/exposed-ip-addresses: "54.247.20.195,54.76.118.103"
spec:
  resourceRef:
    apiVersion: networking.istio.io/v1
    kind: VirtualService
    matchLabels:
      app: podinfo
  strategy:
    type: failover
    dnsTtlSeconds: 5
    primaryGeoTag: "eu"
